	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x10000100
	DCD Reset_Handler
	
	ALIGN
	
	AREA MY_CODE, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler

	LDR R0, =SRC; // COPYING MEMORY VALUE TO R0
	LDR R1, [R0]; // COPYING R0 MEMORY ADDRESS TO R1
	LDR R2, =DST; // COPYING DST MEMORY VALUE TO R2
	STR R1, [R2]; // WITH R1 AS SOURCE AND [R2] AS DESTINATION, FILL R2 ADDRESS WITH R1 VALUE
	
STOP B STOP
SRC DCD 0x78563412
	
	AREA MY_DATA, DATA, READWRITE
DST DCD 0
	
	
	END