	AREA RESET,DATA,READONLY
	EXPORT __Vectors

__Vectors

	DCD 0X10000100
	DCD Reset_Handler
	ALIGN
	AREA MY_CODE,CODE,READONLY
	ENTRY
	EXPORT Reset_Handler

Reset_Handler

	MOV R0, #6; Array size
	LDR R1, =SRC; R1 <- SRC
	LDR R2, [R1], #4; HOLDS THE FIRST ELEMENT
	LDR R3, =ELE;
	LDR R4, [R3]; HOLDS THE ELEMENT TO BE SEARCHED
	MOV R8, #1;
	
BACK
	CMP R2, R4;
	BEQ RES;
	LDR R2, [R1], #4;
	ADD R8, #1;
	SUBS R0, #1;
	BNE BACK
	

RES
	LDR R5, =DST;	
	STR R8, [R5];



STOP B STOP
SRC DCD 0x14, 0X11, 0X12, 0X15, 0X12, 0X13
ELE DCD 0X13

	AREA MY_DATA,DATA,READWRITE

DST DCD 0
	END